/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Ferramenta.ConexaoBD;
import Model.Logado;
import Model.nivel;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Luciano
 */
public class login extends javax.swing.JFrame {

    ConexaoBD con2 = new ConexaoBD();
    private String senha= "merumeru";
    private String usuario= " ";
    ConexaoBD conex = new ConexaoBD();
    ConexaoBD conexc = new ConexaoBD();
    
    
    
    
    /**
     * Creates new form login
     */
    


    
    public login() {
        initComponents();
        getRootPane().setDefaultButton(JBlogin);
         
        
        
    }
	public void toUpper(JTextField login){
		String s = login.getText().toUpperCase();
		login.setText(s);
                
	}
      
        
    public void Time(){
        int Lsegundos;
        int Lminutos;
        int Lhoras;
        Calendar Ldata;
        try{
            while(true){
                Thread.sleep(1000);
                Ldata = Calendar.getInstance();
                Lhoras = Ldata.get(Calendar.HOUR_OF_DAY);
                Lminutos = Ldata.get(Calendar.MINUTE);
                Lsegundos = Ldata.get(Calendar.SECOND);
                //JOptionPane.showMessageDialog(null, horas + ":" + minutos + ":" + segundos);
                JOptionPane.showMessageDialog(null, Ldata);
                
            }
        }
        catch(InterruptedException e){
            e.printStackTrace();
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pass = new javax.swing.JPasswordField();
        login = new javax.swing.JTextField();
        JBlogin = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuário e Senha");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setToolTipText("DIGITE SUA SENHA PESSOAL AQUI.");
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login.setToolTipText("DIGITE SEU NOME DE USUÁRIO.");
        login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFocusLost(evt);
            }
        });

        JBlogin.setText("Entrar");
        JBlogin.setToolTipText("LOGAR");
        JBlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBlogin.setEnabled(false);
        JBlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBloginActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.setToolTipText("FECHAR PROGRAMA.");
        jBSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CoreSIS - Contrato");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lidea.png"))); // NOI18N
        jLabel2.setToolTipText("IDEA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Usuário:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(pass, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(411, 207));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBloginActionPerformed

        final loanding carregando = new loanding();
        carregando.setVisible(true);
        
        Thread t = new Thread(){
            
            @Override
            public void run(){
                
                
        //con2.conexao();
        Connection conn=null;
        Connection conn2=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        PreparedStatement pstD=null;
        ResultSet rsD=null;
        //Time();
        //Calendar Ldata2;
       //commit
        
        String j=null;
        String mm = "4";
        String Inv = null;
        String dataV = "09/06/2021";
        String nome = null;
        DateFormat nascimento = new SimpleDateFormat("ddmmyyyy");
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); 
	Date date22 = new Date(); 
        String nal = dateFormat.format(date22);
       try {         
           InetAddress address = InetAddress.getLocalHost();  
           NetworkInterface ni = NetworkInterface.getByInetAddress(address);  
           byte[] mac = ni.getHardwareAddress();
           String macAddress = "";
           for (int i = 0; i < mac.length; i++) {             
               //macAddress += (String.format("%02X-", mac[i]));
               macAddress += (String.format("%02X"+mm+"", mac[i]));
                j = macAddress;
                Inv = new StringBuilder(j).reverse().toString();
           }
           //System.out.println(""+Inv);
           
           JOptionPane.showMessageDialog(null, "o codigo mac é: " +j+ "   invertida é: " + Inv);
        } catch (UnknownHostException e) {  
           e.printStackTrace();
        } catch (SocketException e) {  
           e.printStackTrace();  
        }
        
        String nome_U =""+login.getText();
        String pass_U =""+pass.getText();
        conex.conexao();
        conex.executarSql("SELECT *FROM user WHERE usuario ='"+nome_U+"' and senha='"+pass_U+"'");
        
        try{
            if (pass.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "VOCÊ PRECISA DIGITAR SUA SENHA!");
            
            }else if (conex.rs.next()) {
                //JOptionPane.showMessageDialog(null, "PASSOU O PRIMEIRO");
                conexc.conexaon();
                conexc.executarSqln("SELECT *FROM vencimento WHERE lic='"+Inv+"' and datavence='"+dataV+"'");
                if (conexc.rsc.next()){  
                nome = conex.rs.getString("Nome");
                //JOptionPane.showMessageDialog(null, "PASSOU O SEGUNDO" +nome); 
                //String idade = rs.getString("")
                JOptionPane.showMessageDialog(null, "Seja Bem Vindo "+nome);
                        Logado log = new Logado();
                         nivel lvl = new nivel();
                       String lvls = conex.rs.getString("nivel");
                        log.setNome(nome);
                        lvl.setNivel(lvls);
                        Principal obj=new Principal();
                        obj.exportarNome(log);
                        obj.exportarNivel(lvl);
                        obj.setVisible(true); 
                        dispose();
                        //conn.close();
                }else {
                    nome = conex.rs.getString("Nome");
                    JOptionPane.showMessageDialog(null, "DESCULPE "+nome+ " MAS SUA LICENÇA ESTÁ ESPIRADA");
                    
                }    
        
        }else{
                 JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorreto");
                 conexc.desconectan();
                 conex.desconectan();
                 //conn.close();
            }
            
            
                   
            

        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "erro ao conectar com o DB!! (GERAL)" +e);
                
                
                }
        carregando.dispose();
                
            }
            
        };
        t.start();
        
        
    }//GEN-LAST:event_JBloginActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed

        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jBSairActionPerformed

    private void loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFocusLost
        // TODO add your handling code here:
        if(!login.getText().isEmpty()){
              JBlogin.setEnabled(true);
          }else{
              JBlogin.setEnabled(false);
          }
    }//GEN-LAST:event_loginFocusLost

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_passFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBlogin;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the User
     */
   
}
